# Generated by Django 5.1.7 on 2025-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('freelancer', 'کارجو'), ('employer', 'کارفرما')], default='freelancer', max_length=20),
        ),
    ]
